---
- name: Update package cache
  become: true
  ansible.builtin.dnf:
    update_cache: true

- name: Install epel-release
  become: true
  ansible.builtin.dnf:
    name: epel-release
    state: present

- name: Install lynis package
  become: true
  ansible.builtin.dnf:
    name: "{{ lynis_package_name }}"
    state: present
    enablerepo: epel
