---
- name: Install python and pip
  ansible.builtin.include_role:
    name: "{{ item }}"
  loop:
    - ensure-python
    - ensure-pip

- name: Install Ansible
  ansible.builtin.pip:
    name: "ansible=={{ ansible_molecule_ansible_version }}"
    virtualenv: "{{ ansible_molecule_venv }}"
    virtualenv_command: 'python3 -m venv'
    state: present
