---
# tasks file for ansible_molecule
- name: Include node specific install tasks
  ansible.builtin.include_tasks: "install-{{ ansible_os_family }}.yml"

- name: Install requirements
  ansible.builtin.pip:
    virtualenv: "{{ ansible_molecule_venv }}"
    requirements: "molecule/requirements.txt"
    chdir: "{{ zuul_work_dir }}"

- name: Run ansible-molecule
  ansible.builtin.shell:
    cmd: |
      set -e
      . "{{ ansible_molecule_venv }}"/bin/activate
      python -m molecule --debug -v test -s delegated
      python -m molecule --debug -v destroy -s delegated
    chdir: "{{ zuul_work_dir }}"
    executable: /bin/bash
  environment:
    ANSIBLE_ROLE: "{{ ansible_role }}"
  changed_when: true
