---
repositories:
  - name: "appstream"
    description: "{{ansible_distribution }} Stream $releasever - AppStream"
    mirrorlist: "http://mirrorlist.centos.org/?release=$stream&arch=$basearch&repo=AppStream&infra=$infra"
    gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial"
    file: "{{ansible_distribution }}-Stream-AppStream"
  - name: "baseos"
    description: "{{ansible_distribution }} Stream $releasever - BaseOS"
    mirrorlist: "http://mirrorlist.centos.org/?release=$stream&arch=$basearch&repo=BaseOS&infra=$infra"
    gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial"
    file: "{{ansible_distribution }}-Stream-BaseOS"
  - name: "extras"
    description: "{{ansible_distribution }} Stream $releasever - Extras"
    mirrorlist: "http://mirrorlist.centos.org/?release=$stream&arch=$basearch&repo=extras&infra=$infra"
    gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial"
    file: "{{ansible_distribution }}-Stream-Extras"
  - name: "epel"
    description: "Extra Packages for Enterprise Linux $releasever - {{ ansible_architecture }}"
    metalink: "https://mirrors.fedoraproject.org/metalink?repo=epel-$releasever&arch=$basearch&infra=$infra&content=$contentdir"
    gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8"
    file: "epel"
  - name: "epel-modular"
    description: "Extra Packages for Enterprise Linux Modular $releasever - {{ ansible_architecture }}"
    metalink: "https://mirrors.fedoraproject.org/metalink?repo=epel-modular-$releasever&arch=$basearch&infra=$infra&content=$contentdir"
    gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8"
    file: "epel-modular"
