---
- name: Set hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ hostname_name }}"
  notify: Gathers facts about hosts

- name: Copy /etc/hostname
  become: true
  ansible.builtin.template:
    src: config.j2
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644
  notify: Gathers facts about hosts
