---
- name: Set hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ inventory_hostname_short }}"

- name: Copy /etc/hostname
  become: true
  ansible.builtin.template:
    src: config.j2
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644
