---
- name: Restart systemd-resolved service  # noqa no-handler
  become: true
  ansible.builtin.systemd_service:
    name: systemd-resolved.service
    state: restarted
  when:
    - resolved_conf.changed
