---
namespace: osism
name: commons
version: 0.6.0
readme: README.md
authors:
  - OSISM community <info@osism.tech>
description: OSISM common roles
license_file: LICENSE
tags:
  - system
dependencies: {}
repository: https://github.com/osism/ansible-collection-commons.git
documentation: https://docs.osism.tech
homepage: https://www.osism.tech
issues: https://github.com/osism/ansible-collection-commons/issues
