---
namespace: osism
name: commons
version: 999.0.0
readme: README.md
authors:
  - OSISM community <info@osism.tech>
description: OSISM common roles
license_file: LICENSE
tags:
  - osism
  - system
  - cloud
  - infrastructure
dependencies: {}
repository: https://github.com/osism/ansible-collection-commons.git
documentation: https://osism.github.io/docs/guides/configuration-guide/commons/
homepage: https://www.osism.tech
issues: https://github.com/osism/ansible-collection-commons/issues
