---
- name: Remove dropbear ssh initramfs packages
  become: true
  ansible.builtin.apt:
    name: "{{ dropbear_packages }}"
    state: absent
    lock_timeout: "{{ apt_lock_timeout | default(300) }}"
  notify:
    - Update initramfs
  when: ansible_os_family == "Debian"

- name: Remove dropbear artefacts
  ansible.builtin.file:
    dest: /etc/initramfs-tools/conf.d/dropbear.conf
    state: absent

- name: Check if disk already bind to Tang
  become: true
  ansible.builtin.command: "clevis luks list -d {{ clevis_root_disk }} -s {{ clevis_luks_slot }}"
  register: result_clevis_luks_list
  changed_when: false
  failed_when: false

- name: Prepare clevis environment
  ansible.builtin.tempfile:
    state: directory
    suffix: clevis
  register: tmp_clevis_env

- name: Get adv handshake from Tang server
  become: true
  ansible.builtin.uri:
    url: "{{ clevis_tang_url }}/adv"
    dest: "{{ tmp_clevis_env.path }}/adv.jws"
    method: GET
    group: root
    owner: root
    mode: 0400
  when: "result_clevis_luks_list.rc == 1"

- name: Insert the keyfile for luks unlock
  become: true
  ansible.builtin.template:
    src: keyfile.j2
    dest: "{{ tmp_clevis_env.path }}/pass"
    group: root
    owner: root
    mode: 0400
  when: "result_clevis_luks_list.rc == 1"
  notify:
    - Chain Tang pin
    - Enable Tang boot environment
    - "Enable service {{ clevis_service_name }}"
    - Delete clevis environment
