---

- name: Remove dropbear ssh initramfs packages
  become: true
  ansible.builtin.apt:
    name: "{{ dropbear_packages }}"
    state: absent
    lock_timeout: "{{ apt_lock_timeout | default(300) }}"
  notify:
    - Update initramfs

- name: Remove dropbear artefacts
  ansible.builtin.file:
    dest: /etc/initramfs-tools/conf.d/dropbear.conf
    state: absent

- name: "Check if disk already bind to tang"
  become: true
  ansible.builtin.command: "clevis luks list -d {{ clevis_root_disk }} -s 2"
  register: result_clevis_luks_list
  ignore_errors: true
  changed_when: false

- name: Prepare clevis environment
  ansible.builtin.tempfile:
    state: directory
    suffix: clevis
  register: tmp_clevis_env

- name: Get adv handshake from tang server
  become: true
  ansible.builtin.uri:
    url: "{{ clevis_tang_url }}/adv"
    dest: "{{ tmp_clevis_env.path }}/adv.jws"
    method: GET
    group: root
    owner: root
    mode: 0400
  when: "result_clevis_luks_list.rc == 1"

- name: Insert the keyfile for luks unlock
  become: true
  ansible.builtin.template:
    src: keyfile.j2
    dest: "{{ tmp_clevis_env.path }}/pass"
    group: root
    owner: root
    mode: 0400
  when: "result_clevis_luks_list.rc == 1"
  notify:
    - Chain tang pin
    - Enable tang boot environment
    - "Enable service {{ clevis_service_name }}"
    - Delete clevis environment
