---
- name: Gather variables for each operating system
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Include distribution specific package tasks
  ansible.builtin.include_tasks: "install-{{ ansible_os_family }}.yml"

- name: Install tang encryption
  ansible.builtin.include_tasks: "create-tangcrypt.yml"
