---
- name: Gather variables for each operating system
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Include distribution specific package tasks
  ansible.builtin.include_tasks: "package-{{ ansible_os_family }}.yml"
