---
- name: Gather variables for each operating system
  ansible.builtin.include_vars: "{{ ansible_os_family }}-family.yml"

- name: Set required_packages_distribution variable to default value
  ansible.builtin.set_fact:
    required_packages_distribution: "{{ __required_packages_distribution }}"
  when: required_packages_distribution|default(None) == None

- name: Set apt_cache_valid_time variable to default value
  ansible.builtin.set_fact:
    apt_cache_valid_time: "{{ __apt_cache_valid_time }}"
  when: apt_cache_valid_time|default(None) == None

- name: Include distribution specific package tasks
  ansible.builtin.include_tasks: "package-{{ ansible_os_family }}-family.yml"
