---
- name: Wait for apt lock
  become: true
  ansible.builtin.shell: "while fuser /var/lib/dpkg/{{ item }} >/dev/null 2>&1; do sleep 5; done;"
  loop:
    - lock
    - lock-frontend
  changed_when: false

- name: Update package cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"
    lock_timeout: "{{ apt_lock_timeout|default(300) }}"

- name: Wait for apt lock
  become: true
  ansible.builtin.shell: "while fuser /var/lib/dpkg/{{ item }} >/dev/null 2>&1; do sleep 5; done;"
  loop:
    - lock
    - lock-frontend
  changed_when: false

- name: Upgrade packages
  become: true
  ansible.builtin.apt:
    upgrade: dist
    lock_timeout: "{{ apt_lock_timeout|default(300) }}"
  when: upgrade_packages|bool

- name: Wait for apt lock
  become: true
  ansible.builtin.shell: "while fuser /var/lib/dpkg/{{ item }} >/dev/null 2>&1; do sleep 5; done;"
  loop:
    - lock
    - lock-frontend
  changed_when: false

- name: Install required packages
  become: true
  ansible.builtin.apt:
    name: "{{ required_packages }}"
    state: present
    lock_timeout: "{{ apt_lock_timeout|default(300) }}"
