---
- name: Update package cache
  become: true
  ansible.builtin.dnf:
    name: '*'
    update_cache: true
    update_only: true
    state: latest
    lock_timeout: "{{ dnf_lock_timeout | default(300) }}"
  tags:
    - download
    - upgrade

- name: Download upgrade packages
  become: true
  ansible.builtin.dnf:
    name: '*'
    state: latest
    download_only: true
    lock_timeout: "{{ dnf_lock_timeout | default(300) }}"
  when: upgrade_packages | bool
  tags:
    - download

- name: Upgrade packages
  become: true
  ansible.builtin.dnf:
    name: '*'
    state: latest
    lock_timeout: "{{ dnf_lock_timeout | default(300) }}"
  when: upgrade_packages | bool
  tags:
    - upgrade

- name: Download required packages
  become: true
  ansible.builtin.dnf:
    name: "{{ required_packages }}"
    state: present
    download_only: true
    lock_timeout: "{{ dnf_lock_timeout | default(300) }}"
  tags:
    - download

- name: Install required packages
  become: true
  ansible.builtin.dnf:
    name: "{{ required_packages }}"
    state: present
    lock_timeout: "{{ dnf_lock_timeout | default(300) }}"

- name: Remove useless packages from the cache
  become: true
  ansible.builtin.command:
    cmd: "dnf clean all"
  changed_when: false
  when: packages_cleanup | bool

- name: Remove dependencies that are no longer required
  become: true
  ansible.builtin.dnf:
    autoremove: true
    lock_timeout: "{{ dnf_lock_timeout | default(300) }}"
  when: packages_cleanup | bool
