---
- name: Install needrestart package
  become: true
  ansible.builtin.apt:
    name: needrestart
    state: present
    lock_timeout: "{{ apt_lock_timeout | default(300) }}"
  tags:
    - needrestart

- name: Set needrestart mode
  become: true
  ansible.builtin.lineinfile:
    path: /etc/needrestart/needrestart.conf
    regexp: "^#$nrconf{restart} = 'i';"
    line: "$nrconf{restart} = '{{ packages_needrestart_mode }}';"
  tags:
    - needrestart

- name: Set apt_cache_valid_time variable to default value
  ansible.builtin.set_fact:
    apt_cache_valid_time: "{{ __apt_cache_valid_time }}"
  when: apt_cache_valid_time|default(None) == None
  tags:
    - download
    - upgrade

- name: Update package cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"
    lock_timeout: "{{ apt_lock_timeout | default(300) }}"
  tags:
    - download
    - upgrade

# NOTE Download only not possible with ansible.builtin.apt.
- name: Download upgrade packages  # noqa command-instead-of-module
  become: true
  ansible.builtin.command:
    apt-get dist-upgrade --yes --download-only
  register: result_download
  changed_when:
    - result_download.rc == 0
    - "'Get' not in result_download.stdout"
  failed_when:
    - result_download.rc != 0
  tags:
    - download

- name: Upgrade packages
  become: true
  ansible.builtin.apt:
    upgrade: dist
    lock_timeout: "{{ apt_lock_timeout | default(300) }}"
  when: upgrade_packages | bool
  tags:
    - upgrade

# NOTE Download only not possible with ansible.builtin.apt.
- name: Download required packages  # noqa command-instead-of-module
  become: true
  ansible.builtin.command:
    apt-get install {{ required_packages | join(" ") }} --yes --download-only
  register: result_download
  changed_when:
    - result_download.rc == 0
    - "'Get' not in result_download.stdout"
  failed_when:
    - result_download.rc != 0
  tags:
    - download

- name: Install required packages
  become: true
  ansible.builtin.apt:
    name: "{{ required_packages }}"
    state: present
    lock_timeout: "{{ apt_lock_timeout | default(300) }}"

- name: Remove useless packages from the cache
  become: true
  ansible.builtin.apt:
    autoclean: true
    lock_timeout: "{{ apt_lock_timeout | default(300) }}"
  when: packages_cleanup | bool

- name: Remove dependencies that are no longer required
  become: true
  ansible.builtin.apt:
    autoremove: true
    lock_timeout: "{{ apt_lock_timeout | default(300) }}"
  when: packages_cleanup | bool
