---
- name: Update package cache
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Install required packages
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - gpg

- name: Add repository gpg key
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [ arch=amd64 ] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
    update_cache: true
    mode: 0644

- name: Update package cache
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Remove moby-compose package
  become: true
  ansible.builtin.apt:
    name: moby-compose
    state: absent
