---
- name: Debian specific tasks
  become: true
  block:
    - name: Install required packages
      ansible.builtin.apt:
        name: apt-transport-https
        state: present

    - name: Add repository gpg key
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"

    - name: Add repository
      ansible.builtin.apt_repository:
        repo: "deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker
        update_cache: true
        mode: 0644

    - name: Remove moby-compose package
      ansible.builtin.apt:
        name: moby-compose
        state: absent
  when: "'Debian' in ansible_os_family"

- name: RedHat specific tasks
  become: true
  block:
    - name: Install required packages
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2

    - name: Add repository
      ansible.builtin.yum_repository:
        name: docker-ce
        description: Docker CE Stable - $basearch
        baseurl: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/{{ ansible_distribution_version }}/{{ 'aarch64' if ansible_architecture == 'arm64' else ansible_architecture }}/stable"
        gpgcheck: yes
        enabled: yes
        gpgkey: https://download.docker.com/linux/centos/gpg

    - name: Remove moby-compose package
      ansible.builtin.dnf:
        name: moby-compose
        state: absent
  when: "'RedHat' in ansible_os_family"
