---
- name: Debian specific tasks
  become: true
  block:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install required packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - gpg

    - name: Add repository gpg key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add repository
      ansible.builtin.apt_repository:
        repo: "deb [ arch=amd64 ] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker
        update_cache: true
        mode: 0644

    - name: Update package cache
      ansible.builtin.apt:
        update_cache: true

    - name: Remove moby-compose package
      ansible.builtin.apt:
        name: moby-compose
        state: absent
  when: "'Debian' in ansible_os_family"

- name: RedHat specific tasks
  become: true
  block:
    - name: Update package cache
      ansible.builtin.dnf:
        update_cache: yes

    - name: Install required packages
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      loop:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2

    - name: Add repository
      ansible.builtin.yum_repository:
        name: docker-ce
        description: Docker CE Stable - $basearch
        baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
        gpgcheck: yes
        enabled: yes
        gpgkey: https://download.docker.com/linux/centos/gpg

    - name: Remove moby-compose package
      ansible.builtin.yum:
        name: moby-compose
        state: absent
  when: "'RedHat' in ansible_os_family"
