---
- name: Debian specific tasks
  block:
    - name: Update package cache
      become: true
      ansible.builtin.apt:
        update_cache: true

    - name: Install ufw package
      become: true
      ansible.builtin.apt:
        name: ufw
        state: present
  when: "'Debian' in ansible_os_family"

- name: RedHat specific tasks
  block:
    - name: Update package cache
      ansible.builtin.dnf:
        update_cache: yes
      become: true

    - name: Install epel-release
      ansible.builtin.dnf:
        name: epel-release
        state: present
      become: true

    - name: Install ufw package
      ansible.builtin.dnf:
        name: ufw
        state: present
        enablerepo: epel
      become: true
  when: "'RedHat' in ansible_os_family"
