---
- name: Install required packages on Debian
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - libpam-modules
    - openssh-server
    - update-motd
  when: "'Debian' in ansible_os_family"

- name: Install required packages on RedHat
  become: true
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - pam
    - openssh-server
  when: "'RedHat' in ansible_os_family"
