---
- name: Debian specific tasks
  become: true
  block:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install gpg package
      ansible.builtin.apt:
        name: gpg
        state: present
  when: "'Debian' in ansible_os_family"

- name: RedHat specific tasks
  become: true
  block:
    - name: Update package cache
      ansible.builtin.dnf:
        update_cache: yes

    - name: Install gpg package
      ansible.builtin.dnf:
        name: gpg
        state: present
  when: "'RedHat' in ansible_os_family"
