---

#  Preparing the vault and executing the role is the test

- name: Include Docker and HashiCorp Vault deployment
  ansible.builtin.include: vault_setup.yml

- name: Make sure that required module for ansible-modules-hashivault is installed
  ansible.builtin.pip:
    name: hvac
    virtualenv: /home/zuul/venv

- name: Include prepared vault variables
  ansible.builtin.include_vars:
    file: "{{ prepared_vars_path }}/vault_init.yml"

- name: Unseal the vault
  ansible.builtin.include_role:
    name: vault_unseal

#  After the prepare step the role itself is tested in the converge step
