---

#  Preparing the vault and executing the role is the test

- name: Include Docker and HashiCorp Vault deployment
  ansible.builtin.include: vault_setup.yml

- name: Create mock secrets
  set_fact:
    vault_yml: |
      ---
      mock_secret_1: "supersecret"

- name: Export mock secrets
  ansible.builtin.copy:
    dest: "{{ vault_secrets_path }}"
    content: "{{ vault_yml }}"
    mode: '0755'

- name: Make sure that required module for ansible-modules-hashivault is installed
  ansible.builtin.pip:
    name: hvac
    virtualenv: /home/zuul/venv

- name: Include prepared vault variables
  ansible.builtin.include_vars:
    file: "{{ prepared_vars_path }}/vault_import.yml"

- name: Unseal the vault
  ansible.builtin.include_role:
    name: vault_unseal

- name: Init the vault
  ansible.builtin.include_role:
    name: vault_init

#  After the prepare step the role itself is tested in the converge step
