---
- name: Clone configuration repository (ssh / with auth) with branch {{ configuration_git_version }}
  ansible.builtin.git:
    repo: "{{ configuration_git_repository_url }}"
    dest: "{{ configuration_directory }}"
    version: "{{ configuration_git_version }}"
    key_file: "{{ configuration_git_private_key_file }}"
    accept_hostkey: true
    umask: "0007"
    force: true
  when: configuration_git_protocol == 'ssh'

- name: Clone configuration repository (without auth or personal access token) with branch {{ configuration_git_version }}
  ansible.builtin.git:
    repo: "{{ configuration_git_repository_url }}"
    dest: "{{ configuration_directory }}"
    version: "{{ configuration_git_version }}"
    accept_hostkey: true
    force: true
    umask: "0007"
  when: (configuration_git_protocol == 'ssh' and (configuration_git_private_key is not defined or not configuration_git_private_key | length)) or
        configuration_git_protocol != 'ssh'
  # NOTE: No logs are output to avoid leaking a PAT if it is used as a username.
  no_log: true

- name: Set permissions of configuration directory
  ansible.builtin.file:
    path: "{{ configuration_directory }}"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0770
