---
- name: Disable fastmirror plugin
  become: true
  community.general.ini_file:
    path: /etc/yum/pluginconf.d/fastestmirror.conf
    section: main
    option: enabled
    value: 0
    mode: 0644

- name: Configure proxy parameters for yum
  become: true
  community.general.ini_file:
    path: /etc/yum.conf
    section: main
    option: proxy
    value: "{{ proxy_proxies['https']default(proxy_proxies['http']) }}"
    mode: 0644
