---
- name: Install packages required by docker login
  become: true
  ansible.builtin.apt:
    name: ["gnupg2", "pass"]
    state: present
    lock_timeout: "{{ apt_lock_timeout | default(300) }}"

- name: Login to registry and force re-authorization
  become: true
  community.docker.docker_login:
    registry: "{{ docker_login_registry }}"
    username: "{{ docker_login_username }}"
    password: "{{ docker_login_password }}"
    reauthorize: true
