---
- name: Cleanup installed packages
  become: true
  ansible.builtin.dnf:
    name: "{{ cleanup_packages }}"
    state: absent

- name: Remove useless packages from the cache
  become: true
  ansible.builtin.command:
    cmd: "dnf clean all"
    warn: false
  changed_when: false

- name: Remove dependencies that are no longer required
  become: true
  ansible.builtin.dnf:
    autoremove: true
