---
- name: Disable dnf-makecache timers
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}.timer"
    state: stopped
    enabled: false
  when: item + ".timer" in services
  loop:
    - dnf-makecache
