---
- name: Disable apt-daily timers
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}.timer"
    state: stopped
    enabled: false
  when: item + ".timer" in services
  loop:
    - apt-daily-upgrade
    - apt-daily
