---
- name: Remove update-motd package
  become: true
  ansible.builtin.apt:
    name: update-motd
    state: absent
    lock_timeout: "{{ apt_lock_timeout | default(300) }}"

- name: Check if /etc/default/motd-news exists
  ansible.builtin.stat:
    path: /etc/default/motd-news
  register: default_motd_news_stat

- name: Disable the dynamic MOTD news service
  become: true
  ansible.builtin.lineinfile:
    path: /etc/default/motd-news
    regexp: "^ENABLED="
    line: "ENABLED=0"
  when: default_motd_news_stat.stat.exists

- name: Disable dynamic motd banner in pam configuration for ssh
  become: true
  ansible.builtin.replace:
    path: /etc/pam.d/sshd
    regexp: "{{ item.regex }}"
    replace: "{{ item.replace }}"
    mode: 0644
  loop:
    - regex: '^session.*optional.*pam_motd.so.*motd=/run/motd.dynamic$'
      replace: '# session  optional  pam_motd.so  motd=/run/motd.dynamic'

    # NOTE: The ssh banner directive is used to output /etc/motd.
    - regex: '^session.*optional.*pam_motd.so.*noupdate$'
      replace: '# session  optional  pam_motd.so  noupdate'

- name: Disable dynamic motd banner in pam configuration for login
  become: true
  ansible.builtin.replace:
    path: /etc/pam.d/login
    regexp: "{{ item.regex }}"
    replace: "{{ item.replace }}"
    mode: 0644
  loop:
    - regex: '^session.*optional.*pam_motd.so.*motd=/run/motd.dynamic$'
      replace: '# session  optional  pam_motd.so  motd=/run/motd.dynamic'
