---
- name: Remove update-motd package
  become: true
  ansible.builtin.apt:
    name: update-motd
    state: absent
    lock_timeout: "{{ apt_lock_timeout|default(300) }}"

- name: Stop motd-news timer
  become: true
  ansible.builtin.service:
    name: motd-news.timer
    state: stopped
    enabled: false
  when: "'motd-news.timer' in ansible_facts.services"

- name: Stop motd-news service
  become: true
  ansible.builtin.service:
    name: motd-news.service
    state: stopped
    enabled: false
  when: "'motd-news.service' in ansible_facts.services"

- name: Disable dynamic motd banner in pam configuration for ssh
  become: true
  ansible.builtin.replace:
    path: /etc/pam.d/sshd
    regexp: "{{ item.regex }}"
    replace: "{{ item.replace }}"
    mode: 0644
  loop:
    - regex: '^session.*optional.*pam_motd.so.*motd=/run/motd.dynamic$'
      replace: '# session  optional  pam_motd.so  motd=/run/motd.dynamic'

    # NOTE: The ssh banner directive is used to output /etc/motd.
    - regex: '^session.*optional.*pam_motd.so.*noupdate$'
      replace: '# session  optional  pam_motd.so  noupdate'

- name: Disable dynamic motd banner in pam configuration for login
  become: true
  ansible.builtin.replace:
    path: /etc/pam.d/login
    regexp: "{{ item.regex }}"
    replace: "{{ item.replace }}"
    mode: 0644
  loop:
    - regex: '^session.*optional.*pam_motd.so.*motd=/run/motd.dynamic$'
      replace: '# session  optional  pam_motd.so  motd=/run/motd.dynamic'
