---
- name: Wait for apt lock
  ansible.builtin.shell: "while fuser /var/lib/dpkg/{{ item }} >/dev/null 2>&1; do sleep 5; done;"
  loop:
    - lock
    - lock-frontend
  changed_when: false

- name: Install microcode packages
  become: true
  ansible.builtin.apt:
    name: "{{ microcode_packages }}"
    state: present
