---
- name: Install Python
  ansible.builtin.include_role:
    name: "{{ item }}"
  loop:
    - ensure-python
    - ensure-pip

- name: Install pip module black
  ansible.builtin.pip:
    name: black
    state: latest
    virtualenv: "{{ python_venv_dir }}"
    virtualenv_command: 'python3 -m venv'
    chdir: "{{ zuul_work_dir }}"

- name: Format code with Black if there is nothing to exclude
  ansible.builtin.command:
    cmd: "{{ python_venv_dir }}/bin/python3 -m black --check ."
    chdir: "{{ zuul_work_dir }}"
  when: black_excluded_dir == ""
  changed_when: false

- name: Format code with Black if there is an exclusion
  ansible.builtin.command:
    cmd: "{{ python_venv_dir }}/bin/python3 -m black --check . --exclude {{ black_excluded_dir }}"
    chdir: "{{ zuul_work_dir }}"
  when: black_excluded_dir != ""
  changed_when: false
