---
- name: Include distribution specific install tasks
  ansible.builtin.include_tasks: "install-{{ ansible_os_family }}.yml"

- name: Include config tasks
  ansible.builtin.include_tasks: config.yml
