---
- name: Install required packages
  become: true
  ansible.builtin.apt:
    name: ['uidmap', '{{ podman_package_name }}']
    state: present
    lock_timeout: "{{ apt_lock_timeout|default(300) }}"
