---
- name: Wait for apt lock
  ansible.builtin.shell: "while fuser /var/lib/dpkg/{{ item }} >/dev/null 2>&1; do sleep 5; done;"
  loop:
    - lock
    - lock-frontend
  when: kubectl_configure_repository|bool
  changed_when: false

- name: Install apt-transport-https package
  become: true
  ansible.builtin.apt:
    name: apt-transport-https
    state: present
  when: kubectl_configure_repository|bool

- name: Add repository gpg key
  become: true
  ansible.builtin.apt_key:
    url: "{{ kubectl_debian_repository_key }}"
  when: kubectl_configure_repository|bool

- name: Add repository
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ kubectl_debian_repository }}"
    state: present
    filename: kubectl
    update_cache: true
    mode: 0600
  when: kubectl_configure_repository|bool

- name: Wait for apt lock
  ansible.builtin.shell: "while fuser /var/lib/dpkg/{{ item }} >/dev/null 2>&1; do sleep 5; done;"
  loop:
    - lock
    - lock-frontend
  changed_when: false

- name: "Install {{ kubectl_package_name }} package"
  become: true
  ansible.builtin.apt:
    name: "{{ kubectl_package_name }}"
    state: present
