---
- name: Remove old architecture-dependent repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [ arch=amd64 signed-by=/usr/share/keyrings/kubectl.gpg ] https://apt.kubernetes.io/ kubernetes-xenial main"
    state: absent
    filename: kubectl
  when: kubectl_configure_repository|bool

- name: Install apt-transport-https package
  become: true
  ansible.builtin.apt:
    name: apt-transport-https
    state: present
    lock_timeout: "{{ apt_lock_timeout | default(300) }}"
  when: kubectl_configure_repository | bool

- name: Add repository gpg key
  become: true
  ansible.builtin.shell:
    cmd: |
      set -eo pipefail
      curl -fsSL {{ kubectl_debian_repository_key }} | gpg --dearmor --batch --no-tty -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg-new
      mv /etc/apt/keyrings/kubernetes-apt-keyring.gpg-new /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    executable: /bin/bash
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  when: kubectl_configure_repository | bool

- name: Set permissions of gpg key
  become: true
  ansible.builtin.file:
    path: "/etc/apt/keyrings/kubernetes-apt-keyring.gpg"
    owner: root
    group: root
    mode: 0644
  when: kubectl_configure_repository | bool

- name: Add repository Debian
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ kubectl_debian_repository }}"
    state: present
    filename: kubectl
    update_cache: true
    mode: 0644
  when: kubectl_configure_repository | bool

- name: Install required packages
  become: true
  ansible.builtin.apt:
    name: "{{ kubectl_required_packages }}"
    state: present
    lock_timeout: "{{ apt_lock_timeout | default(300) }}"

- name: Remove kubectl symlink
  become: true
  ansible.builtin.file:
    path: /usr/local/bin/kubectl
    state: absent
