---
- name: Add repository RedHat
  become: true
  ansible.builtin.yum_repository:
    name: kubectl
    description: "K8s repository"
    baseurl: "{{ kubectl_redhat_repository }}"
    gpgcheck: true
    enabled: true
    gpgkey: "{{ kubectl_redhat_repository_key }}"
    file: /etc/yum.repos.d/kubernetes
    mode: 0644
  when: kubectl_configure_repository | bool

- name: Install required packages
  become: true
  ansible.builtin.dnf:
    name: "{{ kubectl_required_packages }}"
    state: present
    lock_timeout: "{{ dnf_lock_timeout | default(300) }}"
