---
- name: Install apt-transport-https package
  become: true
  ansible.builtin.apt:
    name: apt-transport-https
    state: present
    lock_timeout: "{{ apt_lock_timeout | default(300) }}"
  when: kubectl_configure_repository | bool

- name: Download and install GPG key into /etc/apt/keyrings
  become: true
  ansible.builtin.shell:
    cmd: |
      set -eo pipefail
      curl -fsSL "{{ kubectl_debian_repository_key }}" | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    executable: /bin/bash
  when: kubectl_configure_repository | bool
  changed_when: false

- name: Add repository
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ kubectl_debian_repository }}"
    state: present
    filename: kubectl
    update_cache: true
    mode: 0644
  when: kubectl_configure_repository | bool

- name: "Install package {{ kubectl_package_name }}"
  become: true
  ansible.builtin.apt:
    name: "{{ kubectl_package_name }}"
    state: present
    lock_timeout: "{{ apt_lock_timeout | default(300) }}"
