---
- name: List existing configuration files
  command: "find {{ network_netplan_path }} -type f"
  changed_when: false
  register: network_existing_files

# NOTE: depending on change the result stores dest or path
#       check mode doesn't store any of those so use module args

- name: Set network_configured_files fact
  set_fact:
    network_configured_files: >-
      [{% for item in network_netplan_managed_files | default([]) -%}
        u"{{ network_netplan_path }}/{{ item }}"
        {{ '' if loop.last else ',' }}
      {%- endfor %}]

- name: Remove unused configuration files
  become: true
  file:
    dest: "{{ item }}"
    state: absent
  when: item not in network_configured_files
  with_items: "{{ network_existing_files.stdout_lines | default([]) }}"
