---
- name: Gather variables for each operating system
  ansible.builtin.include_vars: "{{ ansible_os_family }}-family.yml"

- name: Include type specific tasks
  ansible.builtin.include_tasks: "{{ network_type }}-{{ ansible_os_family }}-family.yml"

- name: Include dummy interfaces
  ansible.builtin.include_tasks: dummy-interfaces.yml
  when: network_dummy_interfaces | length > 0

- name: Include vxlan interfaces
  ansible.builtin.include_tasks: vxlan-interfaces.yml
  when: network_vxlan_interfaces | length > 0
