---
- name: Include type specific tasks
  ansible.builtin.include_tasks: "type-{{ network_type }}.yml"

- name: Include dummy interfaces
  ansible.builtin.include_tasks: dummy-interfaces.yml
  when: network_dummy_interfaces|length > 0
