---
- name: Install epel-release package
  become: true
  ansible.builtin.dnf:
    name: epel-release
    state: present
    lock_timeout: "{{ dnf_lock_timeout | default(60) }}"

- name: Enable EPEL repository
  become: true
  ansible.builtin.command:
    cmd: dnf config-manager --set-enabled epel
  changed_when: true

- name: Update package cache
  become: true
  ansible.builtin.dnf:
    update_cache: true
    lock_timeout: "{{ dnf_lock_timeout | default(60) }}"

- name: Add mirrorlist repositories
  become: true
  ansible.builtin.yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    mirrorlist: "{{ item.mirrorlist }}"
    gpgkey: "{{ item.gpgkey }}"
    gpgcheck: true
    enabled: true
    file: "{{ item.file }}"
  loop: "{{ repositories }}"
  when: item.mirrorlist is defined

- name: Add metalink repositories
  become: true
  ansible.builtin.yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    metalink: "{{ item.metalink }}"
    gpgkey: "{{ item.gpgkey }}"
    gpgcheck: true
    enabled: true
    file: "{{ item.file }}"
  loop: "{{ repositories }}"
  when: item.metalink is defined
