---
- name: Copy ufw.conf configuration file
  become: true
  ansible.builtin.template:
    src: ufw.conf.j2
    dest: /etc/ufw/ufw.conf
    mode: 0644
  notify: "Restart service {{ ufw_service_name }}"

- name: "Start service {{ ufw_service_name }}"
  become: true
  ansible.builtin.service:
    name: "{{ ufw_service_name }}"
    state: started
    enabled: true
