---
docker_debian_repository_arch: amd64
docker_debian_repository_key: https://download.docker.com/linux/ubuntu/gpg
docker_debian_repository: "deb [ arch={{ docker_debian_repository_arch }} ] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
