---
- name: Install ca-certificates package on Debian
  become: true
  ansible.builtin.apt:
    name: "{{ certificates_ca_package_name }}"
    state: present
    lock_timeout: "{{ lock_timeout | default(300) }}"
