---
- name: Install ca-certificates package
  become: true
  ansible.builtin.apt:
    name: "{{ certificates_ca_package_name }}"
    state: present
    lock_timeout: "{{ apt_lock_timeout|default(300) }}"
