---
- name: Install ca-certificates package on RHEL
  become: true
  ansible.builtin.dnf:
    name: "{{ certificates_ca_package_name }}"
    state: present
    lock_timeout: "{{ dnf_lock_timeout | default(300) }}"
