---
- name: Converge
  hosts: all

  tasks:
    - name: Include required variables
      ansible.builtin.include_vars:
        file: "vars/{{ molecule_role }}.yml"

    - name: Include prepared variables
      ansible.builtin.include_vars:
        file: "{{ prepared_vars_path }}/{{ molecule_role }}.yml"
      failed_when: false

    - name: "Include role {{ molecule_role }}"
      ansible.builtin.include_role:
        name: "{{ molecule_role }}"
