---
- name: Wait for apt lock
  shell: "while fuser /var/lib/dpkg/{{ item }} >/dev/null 2>&1; do sleep 5; done;"
  loop:
    - lock
    - lock-frontend
  changed_when: false

- name: Ensure docker-compose is not installed
  become: true
  apt:
    name: docker-compose
    state: absent

- name: Block installation of docker-compose package
  become: true
  copy:
    content: |
      Package: docker-compose
      Pin: version *
      Pin-Priority: -1
    mode: 0644
    dest: /etc/apt/preferences.d/docker-compose

- name: Copy docker-compose script
  become: true
  template:
    src: docker-compose.j2
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0755
