---
- name: Wait for apt lock
  ansible.builtin.shell: "while fuser /var/lib/dpkg/{{ item }} >/dev/null 2>&1; do sleep 5; done;"
  loop:
    - lock
    - lock-frontend
  changed_when: false

- name: Install tzdata package
  become: true
  ansible.builtin.apt:
    name: tzdata
    state: present
    update_cache: true

- name: "Set timezone to {{ timezone_name }}"
  become: true
  community.general.timezone:
    hwclock: "{{ timezone_hwclock }}"
    name: "{{ timezone_name }}"
