---
- name: Install tzdata package
  become: true
  ansible.builtin.package:
    name: tzdata
    state: present
    lock_timeout: "{{ dnf_lock_timeout | default(300) }}"

# NOTE: We use a variable for the value of hwclock at this point. However,
# ansible-lint expects UTC or Local and does not resolve the default value
# of the variable. Therefore, the rule args[module] is ignored at this point.
- name: "Set timezone to {{ timezone_name }}"  # noqa:args[module]
  become: true
  community.general.timezone:
    hwclock: "{{ timezone_hwclock }}"
    name: "{{ timezone_name }}"

- name: Create /etc/adjtime file
  become: true
  ansible.builtin.file:
    path: /etc/adjtime
    state: touch
    mode: '0644'
  when: "'RedHat' in ansible_os_family"

- name: Ensure UTC in /etc/adjtime
  become: true
  ansible.builtin.lineinfile:
    path: /etc/adjtime
    line: "{{ timezone_hwclock }}"
  when: "'RedHat' in ansible_os_family"
