---
- name: Wait for apt lock
  ansible.builtin.shell: "while fuser /var/lib/dpkg/{{ item }} >/dev/null 2>&1; do sleep 5; done;"
  loop:
    - lock
    - lock-frontend
  changed_when: false

- name: Install tzdata package
  become: true
  ansible.builtin.apt:
    name: tzdata
    state: present
    lock_timeout: "{{ apt_lock_timeout|default(300) }}"

# NOTE: We use a variable for the value of hwclock at this point. However,
# ansible-lint expects UTC or Local and does not resolve the default value
# of the variable. Therefore, the rule args[module] is ignored at this point.
- name: "Set timezone to {{ timezone_name }}"  # # noqa: args[module]
  become: true
  community.general.timezone:
    hwclock: "{{ timezone_hwclock }}"
    name: "{{ timezone_name }}"
