---
- name: Force update of package cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ repository_cache_valid_time }}"
    lock_timeout: "{{ apt_lock_timeout | default(300) }}"
