---
- name: "Set limits on domain {{ item.key }}"
  become: true
  community.general.pam_limits:  # noqa osism-fqcn
    domain: "{{ item.key }}"
    limit_type: "{{ item_in_block.type }}"
    limit_item: "{{ item_in_block.item }}"
    value: "{{ item_in_block.value }}"
  loop: "{{ item.value }}"
  loop_control:
    loop_var: item_in_block
