---
- name: Copy /etc/hosts file
  become: true
  ansible.builtin.template:
    src: "hosts-template.j2"
    dest: "{{ hosts_file }}"
    owner: root
    group: root
    mode: 0644
    backup: "{{ hosts_file_backup }}"
