---
vault_token: ""

vault_protocol: http
vault_host: vault
vault_port: 8200

vault_url: "{{ vault_protocol }}://{{ vault_host }}:{{ vault_port }}"

vault_secrets_path: /opt/configuration/environments/secrets.yml
